# Generated by Django 4.1.7 on 2023-02-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousesAlatauskij',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_of_rooms', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.FloatField(blank=True, db_column='price', null=True)),
                ('floor', models.FloatField(blank=True, db_column='floor', null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('total_floor', models.FloatField(blank=True, db_column='total_floor', null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'houses_alatauskij',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HousesAlmalinskij',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_of_rooms', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.FloatField(blank=True, db_column='price', null=True)),
                ('floor', models.FloatField(blank=True, db_column='floor', null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('total_floor', models.FloatField(blank=True, db_column='total_floor', null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'houses_almalinskij',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HousesAujezovskij',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_of_rooms', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.FloatField(blank=True, db_column='price', null=True)),
                ('floor', models.FloatField(blank=True, db_column='floor', null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('total_floor', models.FloatField(blank=True, db_column='total_floor', null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'houses_aujezovskij',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HousesBostandykskij',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_of_rooms', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.FloatField(blank=True, db_column='price', null=True)),
                ('floor', models.FloatField(blank=True, db_column='floor', null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('total_floor', models.FloatField(blank=True, db_column='total_floor', null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'houses_bostandykskij',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HousesMedeuskij',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_of_rooms', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.FloatField(blank=True, db_column='price', null=True)),
                ('floor', models.FloatField(blank=True, db_column='floor', null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('total_floor', models.FloatField(blank=True, db_column='total_floor', null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'houses_medeuskij',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HousesNauryzbajskiy',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_of_rooms', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.FloatField(blank=True, db_column='price', null=True)),
                ('floor', models.FloatField(blank=True, db_column='floor', null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('total_floor', models.FloatField(blank=True, db_column='total_floor', null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'houses_nauryzbajskiy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HousesTurksibskij',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_of_rooms', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.FloatField(blank=True, db_column='price', null=True)),
                ('floor', models.FloatField(blank=True, db_column='floor', null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('total_floor', models.FloatField(blank=True, db_column='total_floor', null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'houses_turksibskij',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HousesZhetysuskij',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_of_rooms', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.FloatField(blank=True, db_column='price', null=True)),
                ('floor', models.FloatField(blank=True, db_column='floor', null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('total_floor', models.FloatField(blank=True, db_column='total_floor', null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'houses_zhetysuskij',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.CharField(blank=True, max_length=64, null=True)),
                ('floor', models.FloatField(blank=True, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('total_floor', models.FloatField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=64, null=True)),
                ('prediction', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
