version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432
    
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
    
    volumes:
      - ./data/db:/var/lib/postgresql/data/

  house_website:
    build:
      context: ./house_website
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./house_website:/code/house_website
  
  house_server: 
    build: 
      context: ./house_server
      dockerfile: Dockerfile

    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_HOST: "${POSTGRES_HOST}"

    ports:
      - '8000:8000'

    volumes:
      - ./house_server:/app/house_server

    depends_on:
      - db